package com.university.graduation.domain;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String extraInformation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_id
     *
     * @return the value of class.class_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_id
     *
     * @param classId the value for class.class_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_name
     *
     * @return the value of class.class_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_name
     *
     * @param className the value for class.class_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.extra_information
     *
     * @return the value of class.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getExtraInformation() {
        return extraInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.extra_information
     *
     * @param extraInformation the value for class.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setExtraInformation(String extraInformation) {
        this.extraInformation = extraInformation == null ? null : extraInformation.trim();
    }
}