package com.university.graduation.domain;

public class College {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.college_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.college_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String collegeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String extraInformation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.college_id
     *
     * @return the value of college.college_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.college_id
     *
     * @param collegeId the value for college.college_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.college_name
     *
     * @return the value of college.college_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.college_name
     *
     * @param collegeName the value for college.college_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.extra_information
     *
     * @return the value of college.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getExtraInformation() {
        return extraInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.extra_information
     *
     * @param extraInformation the value for college.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setExtraInformation(String extraInformation) {
        this.extraInformation = extraInformation == null ? null : extraInformation.trim();
    }
}