package com.university.graduation.domain;

public class GraduationLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_link.graduation_link_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer graduationLinkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_link.graduation_link_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String graduationLinkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_link.graduation_link_announcement
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String graduationLinkAnnouncement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_link.graduation_link_id
     *
     * @return the value of graduation_link.graduation_link_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getGraduationLinkId() {
        return graduationLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_link.graduation_link_id
     *
     * @param graduationLinkId the value for graduation_link.graduation_link_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationLinkId(Integer graduationLinkId) {
        this.graduationLinkId = graduationLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_link.graduation_link_name
     *
     * @return the value of graduation_link.graduation_link_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getGraduationLinkName() {
        return graduationLinkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_link.graduation_link_name
     *
     * @param graduationLinkName the value for graduation_link.graduation_link_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationLinkName(String graduationLinkName) {
        this.graduationLinkName = graduationLinkName == null ? null : graduationLinkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_link.graduation_link_announcement
     *
     * @return the value of graduation_link.graduation_link_announcement
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getGraduationLinkAnnouncement() {
        return graduationLinkAnnouncement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_link.graduation_link_announcement
     *
     * @param graduationLinkAnnouncement the value for graduation_link.graduation_link_announcement
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationLinkAnnouncement(String graduationLinkAnnouncement) {
        this.graduationLinkAnnouncement = graduationLinkAnnouncement == null ? null : graduationLinkAnnouncement.trim();
    }
}