package com.university.graduation.domain;

import java.util.Date;

public class GraduationFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_flow.graduation_flow_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer graduationFlowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_flow.graduation_flow_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String graduationFlowName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_flow.graduation_flow_enable_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer graduationFlowEnableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_flow.graduation_flow_year
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer graduationFlowYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_flow.graduation_flow_begin_time
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Date graduationFlowBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_flow.graduation_flow_end_time
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Date graduationFlowEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_flow.graduation_flow_student_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer graduationFlowStudentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_flow.graduation_flow_set_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer graduationFlowSetStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_flow.graduation_flow_id
     *
     * @return the value of graduation_flow.graduation_flow_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getGraduationFlowId() {
        return graduationFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_flow.graduation_flow_id
     *
     * @param graduationFlowId the value for graduation_flow.graduation_flow_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationFlowId(Integer graduationFlowId) {
        this.graduationFlowId = graduationFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_flow.graduation_flow_name
     *
     * @return the value of graduation_flow.graduation_flow_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getGraduationFlowName() {
        return graduationFlowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_flow.graduation_flow_name
     *
     * @param graduationFlowName the value for graduation_flow.graduation_flow_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationFlowName(String graduationFlowName) {
        this.graduationFlowName = graduationFlowName == null ? null : graduationFlowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_flow.graduation_flow_enable_status
     *
     * @return the value of graduation_flow.graduation_flow_enable_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getGraduationFlowEnableStatus() {
        return graduationFlowEnableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_flow.graduation_flow_enable_status
     *
     * @param graduationFlowEnableStatus the value for graduation_flow.graduation_flow_enable_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationFlowEnableStatus(Integer graduationFlowEnableStatus) {
        this.graduationFlowEnableStatus = graduationFlowEnableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_flow.graduation_flow_year
     *
     * @return the value of graduation_flow.graduation_flow_year
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getGraduationFlowYear() {
        return graduationFlowYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_flow.graduation_flow_year
     *
     * @param graduationFlowYear the value for graduation_flow.graduation_flow_year
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationFlowYear(Integer graduationFlowYear) {
        this.graduationFlowYear = graduationFlowYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_flow.graduation_flow_begin_time
     *
     * @return the value of graduation_flow.graduation_flow_begin_time
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Date getGraduationFlowBeginTime() {
        return graduationFlowBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_flow.graduation_flow_begin_time
     *
     * @param graduationFlowBeginTime the value for graduation_flow.graduation_flow_begin_time
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationFlowBeginTime(Date graduationFlowBeginTime) {
        this.graduationFlowBeginTime = graduationFlowBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_flow.graduation_flow_end_time
     *
     * @return the value of graduation_flow.graduation_flow_end_time
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Date getGraduationFlowEndTime() {
        return graduationFlowEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_flow.graduation_flow_end_time
     *
     * @param graduationFlowEndTime the value for graduation_flow.graduation_flow_end_time
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationFlowEndTime(Date graduationFlowEndTime) {
        this.graduationFlowEndTime = graduationFlowEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_flow.graduation_flow_student_num
     *
     * @return the value of graduation_flow.graduation_flow_student_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getGraduationFlowStudentNum() {
        return graduationFlowStudentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_flow.graduation_flow_student_num
     *
     * @param graduationFlowStudentNum the value for graduation_flow.graduation_flow_student_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationFlowStudentNum(Integer graduationFlowStudentNum) {
        this.graduationFlowStudentNum = graduationFlowStudentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_flow.graduation_flow_set_status
     *
     * @return the value of graduation_flow.graduation_flow_set_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getGraduationFlowSetStatus() {
        return graduationFlowSetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_flow.graduation_flow_set_status
     *
     * @param graduationFlowSetStatus the value for graduation_flow.graduation_flow_set_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationFlowSetStatus(Integer graduationFlowSetStatus) {
        this.graduationFlowSetStatus = graduationFlowSetStatus;
    }
}