package com.university.graduation.domain;

public class Specialty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.specialty_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer specialtyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.specialty_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String specialtyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String extraInformation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialty_id
     *
     * @return the value of specialty.specialty_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getSpecialtyId() {
        return specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialty_id
     *
     * @param specialtyId the value for specialty.specialty_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setSpecialtyId(Integer specialtyId) {
        this.specialtyId = specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialty_name
     *
     * @return the value of specialty.specialty_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getSpecialtyName() {
        return specialtyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialty_name
     *
     * @param specialtyName the value for specialty.specialty_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setSpecialtyName(String specialtyName) {
        this.specialtyName = specialtyName == null ? null : specialtyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.extra_information
     *
     * @return the value of specialty.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getExtraInformation() {
        return extraInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.extra_information
     *
     * @param extraInformation the value for specialty.extra_information
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setExtraInformation(String extraInformation) {
        this.extraInformation = extraInformation == null ? null : extraInformation.trim();
    }
}