package com.university.graduation.domain;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_sex
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer studentSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.graduation_year
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer graduationYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id_card_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String idCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.politics_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String politicsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    private String phoneNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_sex
     *
     * @return the value of student.student_sex
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getStudentSex() {
        return studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_sex
     *
     * @param studentSex the value for student.student_sex
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setStudentSex(Integer studentSex) {
        this.studentSex = studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.graduation_year
     *
     * @return the value of student.graduation_year
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getGraduationYear() {
        return graduationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.graduation_year
     *
     * @param graduationYear the value for student.graduation_year
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setGraduationYear(Integer graduationYear) {
        this.graduationYear = graduationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id_card_num
     *
     * @return the value of student.id_card_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id_card_num
     *
     * @param idCardNum the value for student.id_card_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.politics_status
     *
     * @return the value of student.politics_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getPoliticsStatus() {
        return politicsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.politics_status
     *
     * @param politicsStatus the value for student.politics_status
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setPoliticsStatus(String politicsStatus) {
        this.politicsStatus = politicsStatus == null ? null : politicsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone_num
     *
     * @return the value of student.phone_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone_num
     *
     * @param phoneNum the value for student.phone_num
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }
}