package com.university.graduation.domain;

import java.util.Date;

public class sysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.sys_permission_id
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private Integer sysPermissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.sys_permission_name
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private String sysPermissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.resource_type
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.resource_url
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parent_id
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parent_ids
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.state
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.create_time
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.update_time
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.sys_permission_id
     *
     * @return the value of sys_permission.sys_permission_id
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public Integer getSysPermissionId() {
        return sysPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.sys_permission_id
     *
     * @param sysPermissionId the value for sys_permission.sys_permission_id
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setSysPermissionId(Integer sysPermissionId) {
        this.sysPermissionId = sysPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.sys_permission_name
     *
     * @return the value of sys_permission.sys_permission_name
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public String getSysPermissionName() {
        return sysPermissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.sys_permission_name
     *
     * @param sysPermissionName the value for sys_permission.sys_permission_name
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setSysPermissionName(String sysPermissionName) {
        this.sysPermissionName = sysPermissionName == null ? null : sysPermissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.resource_type
     *
     * @return the value of sys_permission.resource_type
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.resource_type
     *
     * @param resourceType the value for sys_permission.resource_type
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.resource_url
     *
     * @return the value of sys_permission.resource_url
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.resource_url
     *
     * @param resourceUrl the value for sys_permission.resource_url
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission
     *
     * @return the value of sys_permission.permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission
     *
     * @param permission the value for sys_permission.permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.parent_id
     *
     * @return the value of sys_permission.parent_id
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.parent_id
     *
     * @param parentId the value for sys_permission.parent_id
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.parent_ids
     *
     * @return the value of sys_permission.parent_ids
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.parent_ids
     *
     * @param parentIds the value for sys_permission.parent_ids
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.state
     *
     * @return the value of sys_permission.state
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.state
     *
     * @param state the value for sys_permission.state
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.create_time
     *
     * @return the value of sys_permission.create_time
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.create_time
     *
     * @param createTime the value for sys_permission.create_time
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.update_time
     *
     * @return the value of sys_permission.update_time
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.update_time
     *
     * @param updateTime the value for sys_permission.update_time
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}