package com.university.graduation.domain;

import java.util.Date;
import java.util.List;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_user_id
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    private Integer sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_username
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    private String sysUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_name
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_password
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    private String sysPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_salt
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    private String sysSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_state
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    private Integer sysState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_time
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    private Date updateTime;


    private List<SysRole> roles;

    public List<SysRole> getRoles() {
        return roles;
    }

    public void setRoles(List<SysRole> roles) {
        this.roles = roles;
    }




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_user_id
     *
     * @return the value of sys_user.sys_user_id
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public Integer getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_user_id
     *
     * @param sysUserId the value for sys_user.sys_user_id
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public void setSysUserId(Integer sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_username
     *
     * @return the value of sys_user.sys_username
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public String getSysUsername() {
        return sysUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_username
     *
     * @param sysUsername the value for sys_user.sys_username
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public void setSysUsername(String sysUsername) {
        this.sysUsername = sysUsername == null ? null : sysUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_name
     *
     * @return the value of sys_user.sys_name
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_name
     *
     * @param sysName the value for sys_user.sys_name
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_password
     *
     * @return the value of sys_user.sys_password
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public String getSysPassword() {
        return sysPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_password
     *
     * @param sysPassword the value for sys_user.sys_password
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public void setSysPassword(String sysPassword) {
        this.sysPassword = sysPassword == null ? null : sysPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_salt
     *
     * @return the value of sys_user.sys_salt
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public String getSysSalt() {
        return sysSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_salt
     *
     * @param sysSalt the value for sys_user.sys_salt
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public void setSysSalt(String sysSalt) {
        this.sysSalt = sysSalt == null ? null : sysSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_state
     *
     * @return the value of sys_user.sys_state
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public Integer getSysState() {
        return sysState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_state
     *
     * @param sysState the value for sys_user.sys_state
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public void setSysState(Integer sysState) {
        this.sysState = sysState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_time
     *
     * @return the value of sys_user.update_time
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_time
     *
     * @param updateTime the value for sys_user.update_time
     *
     * @mbggenerated Tue Oct 02 11:07:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}