package com.university.graduation.dao;

import com.university.graduation.domain.GraduationFlow;
import com.university.graduation.domain.GraduationFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduationFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int countByExample(GraduationFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int deleteByExample(GraduationFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int deleteByPrimaryKey(Integer graduationFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int insert(GraduationFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int insertSelective(GraduationFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    List<GraduationFlow> selectByExample(GraduationFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    GraduationFlow selectByPrimaryKey(Integer graduationFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") GraduationFlow record, @Param("example") GraduationFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int updateByExample(@Param("record") GraduationFlow record, @Param("example") GraduationFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int updateByPrimaryKeySelective(GraduationFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_flow
     *
     * @mbggenerated Wed Oct 03 17:11:10 CST 2018
     */
    int updateByPrimaryKey(GraduationFlow record);
}