package com.university.graduation.dao;

import com.university.graduation.domain.sysPermission;
import com.university.graduation.domain.sysPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int countByExample(sysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int deleteByExample(sysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int deleteByPrimaryKey(Integer sysPermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int insert(sysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int insertSelective(sysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    List<sysPermission> selectByExample(sysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    sysPermission selectByPrimaryKey(Integer sysPermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") sysPermission record, @Param("example") sysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByExample(@Param("record") sysPermission record, @Param("example") sysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByPrimaryKeySelective(sysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByPrimaryKey(sysPermission record);
}