package com.university.graduation.dao;

import com.university.graduation.domain.sysRole;
import com.university.graduation.domain.sysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int countByExample(sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int deleteByExample(sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int deleteByPrimaryKey(String sysRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int insert(sysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int insertSelective(sysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    List<sysRole> selectByExample(sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    sysRole selectByPrimaryKey(String sysRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") sysRole record, @Param("example") sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByExample(@Param("record") sysRole record, @Param("example") sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByPrimaryKeySelective(sysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByPrimaryKey(sysRole record);
}