package com.university.graduation.dao;

import com.university.graduation.domain.sysUser;
import com.university.graduation.domain.sysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int countByExample(sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int deleteByExample(sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int deleteByPrimaryKey(Integer sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int insert(sysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int insertSelective(sysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    List<sysUser> selectByExample(sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    sysUser selectByPrimaryKey(Integer sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") sysUser record, @Param("example") sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByExample(@Param("record") sysUser record, @Param("example") sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByPrimaryKeySelective(sysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Oct 02 10:16:48 CST 2018
     */
    int updateByPrimaryKey(sysUser record);
}